Repository esnet/iperf, pull requests merged in 2018-05, with the labels that each got.

#736 Adding missing word
  src/iperf3.1
Labels: bug, documentation

#729 First try at implementing --extra-data.
  src/iperf.h
  src/iperf3.1
  src/iperf_api.c
  src/iperf_api.h
  src/iperf_locale.c
Labels: enhancement

#744 Add a forgotten cast to fix a glitch in JSON output on CentOS 6.
  src/iperf_api.c
Labels: bug
