Repository esnet/iperf, pull requests merged in 2019-05, with the labels that each got.

#866 Partially revert documentated added in 0c4d599 to reflect reality.
  src/iperf3.1
Labels: bug, documentation

#854 Fix configure when openssl is absent.
  configure
  configure.ac
Labels: bug

#867 Pass repeating_payload option to server
  src/iperf_api.c
Labels: bug

#869 Introduce API functions for repeating_payload option
  src/iperf_api.c
  src/iperf_api.h
Labels: enhancement

#870 Introduce API functions for no_delay option
  src/iperf_api.c
  src/iperf_api.h
Labels: enhancement

#874 enh: Properly include <sys/socket.h> for improved portability.
  src/iperf_api.h
Labels: enhancement, portability
