Repository esnet/iperf, pull requests merged in 2019-06, with the labels that each got.

#877 feat: Authentication failure doesn't count for --one-off.
  src/main.c
Labels: enhancement

#871 Introduce iperf_set_test_logfile API function
  src/iperf_api.c
  src/iperf_api.h
  src/iperf_client_api.c
  src/iperf_server_api.c
Labels: enhancement

#879 Fix display of RELNOTES.md
  RELNOTES.md
Labels: documentation

#885 Fix: Don't allow --port 0 or other invalid values.
  src/iperf_api.c
  src/iperf_api.h
  src/iperf_error.c
Labels: bug

#887 fix: Fix off-by-one memory overwrite crash and memory leaks
  src/iperf_api.c
  src/iperf_auth.c
Labels: bug

#888 fix: Emit appropriate error messages from getaddrinfo(3).
  src/iperf.h
  src/iperf_error.c
  src/iperf_sctp.c
  src/iperf_tcp.c
  src/net.c
Labels: bug

#893 doc: Document --bidir option in manpage.
  src/iperf3.1
Labels: documentation
