Repository esnet/iperf, pull requests merged in 2021-07, with the labels that each got.

#1116 Auto adjustment of test-end condition for file-transfer
  src/iperf_api.c
Labels: enhancement

#1183 docs: Update documentation for -w to reflect what it actually does.
  src/iperf3.1
  src/iperf_locale.c
Labels: documentation

#1174 Added {end}{sum_sent} and {end}{sum_received} to UDP JSON output
  src/iperf_api.c
Labels: bug:json, bug:reverse
