Repository esnet/iperf, pull requests merged in 2021-06, with the labels that each got.

#1155 Updates for autoconf-2.71 (fix #1154)
  configure.ac
Labels: bug, portability

#1176 Remove fsync(2) call after every write to a receiving --file.
  src/iperf_api.c
Labels: enhancement

#1168 Test bandwidth (--bitrate) added to JSON output
  src/iperf_api.c
Labels: enhancement

#1177 enh: Consistently print target_bandwidth in the JSON start section.
  src/iperf_api.c
Labels: bug:json
