Repository esnet/iperf, pull requests merged in 2021-11, with the labels that each got.

#1200 Fix for issue #952 - different json object names for bidir reverse ch…
  src/iperf_api.c
Labels: bug:json

#1227 Fix: Avoid spamming stdout (and JSON output) with a warning.
  src/iperf_api.h
  src/iperf_client_api.c
  src/iperf_udp.c
Labels: bug:json

#1153 Fix --bind-dev options for TCP streams. (#1099)
  src/iperf_tcp.c
  src/net.c
  src/net.h
Labels: bug

#1162 Fix --dscp
  src/dscp.c
  src/iperf3.1
Labels: bug

#1232 Update templates and (some) documentation for discussions
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: documentation
