Repository esnet/iperf, pull requests merged in 2022-05, with the labels that each got.

#1333 Fix memory leak in an error condition.
  src/iperf_api.c
Labels: bug

#1335 Greatly simplify (and fix) behavior of bootstrap.sh.
  bootstrap.sh
Labels: portability

#1310 Added linux version checking in flowlabel.h
  src/flowlabel.h
Labels: enhancement, portability

#1299 Omit help text enhancement
  src/iperf3.1
  src/iperf_locale.c
Labels: documentation
